# Generated by Django 3.2.9 on 2021-11-05 02:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID for PK to user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='email', max_length=50, unique=True)),
                ('name', models.CharField(help_text='user name', max_length=8)),
                ('access_token', models.CharField(help_text='access token to access to social', max_length=200)),
                ('refresh_token', models.CharField(help_text='refresh token to get new access token', max_length=200, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id for PK to this Business Card', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='name', max_length=8)),
                ('mobile_tell', models.CharField(help_text='mobile tell', max_length=20)),
                ('email', models.EmailField(help_text='email', max_length=50, null=True)),
                ('fax', models.CharField(help_text='fax', max_length=20, null=True)),
                ('company', models.CharField(help_text='company', max_length=20)),
                ('company_address', models.CharField(help_text='company address', max_length=100, null=True)),
                ('company_tell', models.CharField(help_text='company tell', max_length=20, null=True)),
                ('com_extension_tell', models.CharField(help_text='company extension tell', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BC_scan.user')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
